### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by arhadnane** [DestructiveVoice/DestructiveFarm#12]
Hi,
Nice work.
what's the default admin and password of application?
thank you

**Comment by borzunov** [comment]
Hi!

Thank you.

You can use the password `1234` and any login to enter. The password can be changed [here](https://github.com/DestructiveVoice/DestructiveFarm/blob/master/server/config.py#L38).

**Comment by arhadnane** [comment]
Nice , it's work :-)

**Comment by borzunov** [comment]
I've also clarified this in the docs :)
